### ISSUE TITLE
A snapshot issue with an attachment

### ISSUE THREAD

**Issue by Avantisankalp** [Avantisankalp/Troubleshooting#26]
From: adebarros@g.harvard.edu<br>
Subject: A snapshot issue with an attachment<br>
First Attachment: sample.pdf https://ift.tt/2MI5EE6<br>
Date: August 15, 2018 at 04:29AM<br>
<br>
<br>
<br>
Label:<br>
<br>
via Gmail

**Comment by Avantisankalp** [comment]
@de-barros is mentioned here

**Comment by de-barros** [comment]
Sending a response including an attachment

**Comment by de-barros** [comment]
Sending a response with an inline picture

[image: image.png]
