### ISSUE TITLE
Dashboard Protocol

### ISSUE THREAD

**Issue by Avantisankalp** [Avantisankalp/Troubleshooting#31]
From: ayub@avantifellows.org<br>
Subject: Dashboard Protocol<br>
First Attachment: D1605913-A58A-47C5-983F-B27F19E6B39D.jpeg https://ift.tt/2MCKI4u<br>
Date: August 17, 2018 at 08:08PM<br>
<br>
Question number 7 why do we have other options in this question because we are only going to observe science and math classes&nbsp;<br>
<br>
Label:<br>
<br>
via Gmail

**Comment by Avantisankalp** [comment]
What does the next page show, when you click on "Others" in Q7?

**Comment by Avantisankalp** [comment]
@debarros This is the current protocol we have for the following situation. I am mentioning in the light of how to best use "Other" option in Q7. 

If the PM finds out that some percentage of the scheduled 11.30-12.30 slot class would be used to firstly teach an unscheduled non-maths/science subject (e.g. Hindi) for some time, and switches to teaching the scheduled maths/science subject (e.g. Biology) for remaining time, then how should the PM fill CLOBS form?

PM should select “A different subject is being taught, NOT maths and NOT science” in Q13 “What is the teacher doing now?”, when a non-maths/science subject is being taught. This would skip the upcoming QUIP. As soon as the scheduled subject begins, the PM can resume selecting relevant options in remaining Snapshot and QUIPs.

**To this protocol, we could add that in Q7, PMs should enter the unscheduled non-Maths/Science subject (e.g. Hindi). And subsequently they can follow the above protocol** Let me know if I can make this final?

**Comment by de-barros** [comment]
On Ayub's question - yes, this "other" option can be removed. I've left it so far, for any unforeseen occasions. But generally, PMs should never observe a non-science, non-math class. The subject question is with respect to the _scheduled / assigned_ subject. 

Therefore, your suggested protocol will also not apply - let's not have a protocol where PMs would go to classes other than math/science.

As to your comment on when other subjects are being taught in a math or science class, we do have the existing protocol in place, where either
(a) the teacher switches for some time >> PM should select “A different subject is being taught, NOT maths and NOT science” in Q13
OR
(b) the teacher ends the class to switch to a non-math/non-science subject >> PM should select that the class ended early.

**Comment by Avantisankalp** [comment]
@de-barros so my protocol was for the case a) that you described. 

Since in case a) you could have a scenario when a scheduled maths class was supposed to happen, but Hindi from previous period is continuing. So since the PM is filling the form as soon as the scheduled time for maths class starts, he could select "Other" and write Hindi there. And later at end of the form, write that subject "actually" taught for majority of class was "Maths".

Other way to do tackle this is, we let the "Other" option remain. But tell PMs to continue marking it as Maths in Q7 since that is originally scheduled. But in 1st snapshot, if Hindi continues from previous period, then they mark as "A different subject is being taught, NOT maths and NOT science” in Q13. **This is in fact what is currently happening also in field.** So my question is should we let this be, or switch to the protocol mentioned in last para?

**Comment by de-barros** [comment]
let's reserve this field for the _scheduled_ class - so this should always be math / science. there should't be any occasion where "other" gets selected. also, what's currently happening in the field sounds right

**Comment by Avantisankalp** [comment]
@de-barros Got it! 

@ayubavantifellows @bijetaavantifellows @shriramavantifellows @shahneyavantifellows @dulanavantifellows @monikaavantifellows Please read the thread of comments above - in Q7, please do NOT select "Other" option ever. Always select the subject which was _scheduled_ to be taught. In case, an _unscheduled non-maths/science_ subject is taught, then in Snapshot, please select "A different subject is being taught, NOT maths and NOT science" in Q13. 

**PMs post "okay" when you have read and understood.**

**Comment by ayubavantifellows** [comment]
Okay
