### ISSUE TITLE
Dashboard bug

### ISSUE THREAD

**Issue by Avantisankalp** [Avantisankalp/Troubleshooting#32]
From: bijeta@avantifellows.org<br>
Subject: Dashboard bug<br>
First Attachment: August 21, 2018 at 05:30AM https://ift.tt/2L9q8UB<br>
Date: August 21, 2018 at 12:01PM<br>
<br>
Option with SPM obs and OTP not working Once I take the videos, the clob form crashes and I have to rest at again. Should I use this third option or continue with only the first option?<br>
<br>
Label:<br>
<br>
via Gmail

**Comment by Avantisankalp** [comment]
1st option - use when you observe class alone as a pm for the school assigned to you
2nd option - use when you are a PM and someone senior visits to observe with you
3rd option - use when you accompany a PM

@bijetaavantifellows

**Comment by bijetaavantifellows** [comment]
@Avantisankalp 3rd option is not working. It throws an error when it asks to capture a video. Once video is shot and closed, the form is unable to resume from that position and does not allow me to move forward.

**Comment by Avantisankalp** [comment]
@debarros Would you know why this error is occuring?

**Comment by Avantisankalp** [comment]
@bijetaavantifellows meanwhile, could you type out what the error text says?

**Comment by bijetaavantifellows** [comment]
Please find the error text shown in the screenshot attached.

**Comment by bijetaavantifellows** [comment]
error message : "Sorry this form doesn't have a saved position from which
to resume". This happens after i close(save) the recording from the camera
and resume to fill the form .

**Comment by Avantisankalp** [comment]
Resolved with Bijeta!
