### ISSUE TITLE
Dashboard Protocol

### ISSUE THREAD

**Issue by Avantisankalp** [Avantisankalp/Troubleshooting#33]
This is the only time **Dashboard Protocol** is being discussed on email. 

If students are in class but teacher doesnt come to class at all during entire period, then **no need to mark "teacher not in class" in all snapshots**. 

This is what you do - you have to anyway **wait at Attendance for Boys and girls screen**, till teacher comes. This means if you keep waiting for her to come in entire period and she doesn't come, then you move one screen back and select **Nowhere. Class was not held at all, not even a few minutes of it.** Now form will skip all Snapshots and QUIPs.

Please send **Okay** in response to this email.

@ayubavantifellows @monikaavantifellows @dulanavantifellows @shriramavantifellows @shahneyavantifellows @bijetaavantifellows

**Comment by bijetaavantifellows** [comment]
Okay

**Comment by Avantisankalp** [comment]
@panchaliavantifellows

**Comment by Avantisankalp** [comment]
@panchaliavantifellows

**Comment by Avantisankalp** [comment]
@Shahneyalam please respond okay, when you read the above protocol

**Comment by Shriramavantifellows** [comment]
Okay

**Comment by ayubavantifellows** [comment]
Okay

**Comment by monikaavantifellows** [comment]
Okay.

**Comment by Shahneyalam** [comment]
Okay

**Comment by dulanavantifellows** [comment]
Okay
