### ISSUE TITLE
QUIP Bug

### ISSUE THREAD

**Issue by Avantisankalp** [Avantisankalp/Troubleshooting#36]
From: bijeta@avantifellows.org<br>
Subject: QUIP Bug<br>
First Attachment: August 27, 2018 at 05:30AM https://ift.tt/2odWKDH<br>
Date: August 27, 2018 at 07:34PM<br>
<br>
Clobs form is not submitting. It says sending failed. It may be the video recordings done for QUIP. the form had shown 2 errors while filling (shared with Brinda over whatsapp) - 1)&nbsp;Sorry this form doesn't have a saved position from which to resume (post Quip 2) - 2) SurveyCTO form is not responding (post Quip 4/)<br>
<br>
Label:<br>
<br>
via Gmail

**Comment by Avantisankalp** [comment]
@bijetaavantifellows Did the form submit now? After you deleted the tablet media videos from Gallery as per our whatsapp discussion

**Comment by bijetaavantifellows** [comment]
No, its not working still. forms are pending in the folder.

**Comment by Avantisankalp** [comment]
resolved as part of video issue
