### ISSUE TITLE
Audit Form : test additional words in subject

### ISSUE THREAD

**Issue by Avantisankalp** [Avantisankalp/Troubleshooting#48]
From: brinda.sapra@ifmr.ac.in<br>
Subject: Audit Form : test additional words in subject<br>
First Attachment: https://ift.tt/19fNRe4<br>
Date: October 31, 2018 at 10:19PM<br>
<br>
Testing multiple subject words apart from key words. If this works, tag Bijeta, and explain how she can use more words better. Brinda Sapra Research Associate&nbsp; J-PAL South Asia at IFMR&nbsp; +91 9818711607&nbsp;&nbsp;|&nbsp;bsapra@povertyactionlab.org | skype: brindasapra&nbsp; Stay informed:&nbsp;Facebook&nbsp;|&nbsp;Twitter&nbsp;|&nbsp;Newsletters<br>
<br>
Label:<br>
<br>
via Gmail

**Comment by Avantisankalp** [comment]
@bijetaavantifellows See above we can use more informative words for subject, after typing Audit Form, so for instance, you could raise an issue like Audit Form: Generate 1 more common id

**Comment by bijetaavantifellows** [comment]
Noted .
