### ISSUE TITLE
Re: [Avantisankalp/Troubleshooting] Audit Form -raw data fetch

### ISSUE THREAD

**Issue by Avantisankalp** [Avantisankalp/Troubleshooting#74]
From: bijeta@avantifellows.org<br>
Subject: Re: [Avantisankalp/Troubleshooting] Audit Form -raw data fetch<br>
First Attachment:  https://ift.tt/19fNRe4<br>
Date: November 03, 2018 at 05:50PM<br>
<br>

Got it, However, the following details i am not able to read in the raw data file  on teachers details and student strength section wise per grade
for example - (list is not exhaustive)

mstudents 

doj (for teachers)

mastertrainer

TGT or PGT

Permanent /Contract

subject 

On Sat, Nov 3, 2018 at 5:18 PM Avantisankalp  wrote:

@bijetaavantifellows column DH is the last column until the older form updates you had shared. Everytime I update the form with any changes (meaning new fields are added), they append side-wards/rightwards, hence go beyond column DH. Don't follow the order of fields from survey form.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

<br>
<br>
Label: <br>
<br>
via Gmail

**Comment by Avantisankalp** [comment]
@bijetaavantifellows are the columns visible but data not there or columns also not visible?

**Comment by bijetaavantifellows** [comment]
Both.
1) Columns not visible, thus data also not there.
Please check all the groupwise- set of Qs that repeats such as teacher
group data, smartroom group and classroom details group is missing , is
what i understand. I am unable to see teacher name and subjects they are
teaching; section wise student strength and room details, smart room
details .
For teacher group Qs what is the column codes,  is it - 1) teacher 2)
sub_sci_math
? if yes, then these column are not there .

2) Columns there but not data-
As for smart room group - columns are there but data not there.

**Comment by Avantisankalp** [comment]
@bijetaavantifellows please let me know the variable names that you are looking for, its difficult to understand this way. Here is the latest sheet attached below.
[Infra Audit 20180904 adb.xlsx](https://github.com/Avantisankalp/Troubleshooting/files/2547642/Infra.Audit.20180904.adb.xlsx)

**Respond on this thread**

**Comment by Avantisankalp** [comment]
@bijetaavantifellows see now
raw_audit sheet's fomula I have updated, it asks to insert more columns. I dont know how to do that, but I have done the necessary changes in the original sheet that I handle. There should be columns upto AHR in raw_audit sheet cuz thats how many there are in the original sheet from which this dashboard pulls (check the formula) whereas rn there are only upto KN in this raw_audit sheet. You will have to add columns.

**Comment by bijetaavantifellows** [comment]
There are some variable names i can't seem to find it in the list shared.
for example the teacher mapping variables . see image attached. similarly
the strength, section and classroom mapping.

The  variables whose column header is there but no data are mentioned below
(list is not exhaustive as the reason stated above)-

students_ix
students_x
sections_ix
sections_x
classrooms_ix
classrooms_x

smart_power
smart_15amp
smart_5amp
smart_sockets
smart_lockdoor
smart_lockwindows
smart_generator
smart_fuel
smart_inverter
smart_number

Please add @panchaliavantifellows to this thread.

**Comment by Avantisankalp** [comment]
@panchaliavantifellows added Panchali

**Comment by Avantisankalp** [comment]
@bijetaavantifellows  these variables are old variable names, please find the latest variable names in the sheet i attached, thats why you cant find them, they are sth like stu_viii_... e.g. see columns DV onwards

**Comment by bijetaavantifellows** [comment]
Can you let me know the total variable fields there. the number ?  It will
help me in adding the number of columns

**Comment by bijetaavantifellows** [comment]
I am reading from the first tab " survey" in column B- "name" and this ends
at row 155. And there are no other columns beyond "Y - media:video" .
Please let me know if i am reading this sheet incorrectly from my end or
there is something missing like DV column you mentioned in the attached
sheet ?

**Comment by Avantisankalp** [comment]
@bijetaavantifellows you are reading it correctly. There are 902 columns total in that original sheet. Could you lmk if I can close this thread?

**Comment by bijetaavantifellows** [comment]
let me check and get back to you on this in a while.

**Comment by Avantisankalp** [comment]
@bijetaavantifellows this works fine! Just do this always
