### ISSUE TITLE
Audit Form -school list

### ISSUE THREAD

**Issue by Avantisankalp** [Avantisankalp/Troubleshooting#85]
From: bijeta@avantifellows.org<br>
Subject: Audit Form -school list<br>
First Attachment: November 08, 2018 at 05:30AM https://ift.tt/2qBfKxk<br>
Date: November 08, 2018 at 07:10AM<br>
<br>
Hi Brinda, Please see the attached file for the new schools that needs to be added to the Audit Form list of schools in SurveyCTO. See the highlighted ones in the sheet, 86 new schools and 1 district (Salhawas) that needs to be added.&nbsp; Thank you! Bijeta<br>
<br>
Label:<br>
<br>
via Gmail

**Comment by Avantisankalp** [comment]
@bijetaavantifellows could you add the schools in this latest attachment I am sending? Its the same exercise you did earlier. I can upload this one instantly.

[Infra Audit 20181112 bs.xlsx](https://github.com/Avantisankalp/Troubleshooting/files/2571972/Infra.Audit.20181112.bs.xlsx)

**Comment by bijetaavantifellows** [comment]
Hi Brinda,
Please find the new schools added to the sheet as requested.

**Comment by Avantisankalp** [comment]
@bijetaavantifellows I could not find any attachement here. Could you try re-sending the attachment again on Github, and as a precaution also on email?

**Comment by Avantisankalp** [comment]
Done and uploaded. Closing issue now.
