### ISSUE TITLE
Re: [Avantisankalp/Troubleshooting] Re: Audit Form - bug (#83)

### ISSUE THREAD

**Issue by Avantisankalp** [Avantisankalp/Troubleshooting#89]
From: notifications@github.com<br>
Subject: Re: [Avantisankalp/Troubleshooting] Re: Audit Form - bug (#83)<br>
First Attachment:  https://ift.tt/19fNRe4<br>
Date: November 12, 2018 at 09:26AM<br>
<br>
Hi ,
There was no version update that came since yesterday. Can't see the 10th
grade added for Hindi medium.

Also as per the last version upgrade last week there was a query posted
(see attached screenshot ) if this was the solution then I think the series
of Qs is misplaced in the sequence.

On Sun 11 Nov, 2018, 6:15 PM Avantisankalp, 
wrote:

&gt; Closed #83 .
&gt;
&gt; —
&gt; You are receiving this because you were mentioned.
&gt; Reply to this email directly, view it on GitHub
&gt; ,
&gt; or mute the thread
&gt; 
&gt; .
&gt;

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.

<br>
<br>
Label: <br>
<br>
via Gmail

**Comment by Avantisankalp** [comment]
@bijetaavantifellows will get back on Wednesday. I didn't understand this issue yet, will call you on Wednesday.

**Comment by Avantisankalp** [comment]
@bijetaavantifellows I have uploaded a new version on server. 2 things should have been debugged now:
1. When you select "Both" as medium of instruction, then earlier only grade 8 and 9 were being asked, but now grade 10 will also be asked - for questions related to : a) Number of classrooms for this grade b) Select all sections for this grade c) Number of classes held in open spaces d) Student strength in that grade and section

2. Earlier grade 8,9,10 questions were appearing when "Both" mediums were selected. But now those will appear only when either English or Hindi is selected. (re: grp1_3_gr8gr9gr10)

Can you test the form and lmk?

**Comment by bijetaavantifellows** [comment]
Yes, will test it by tomorrow and let you know.
